baseURL = 'https://ljvmiranda921.github.io/gallery'
languageCode = 'en-us'
title = 'gb-gallery'
theme = 'hugo-theme-console'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"
